theme: jekyll-theme-minimal
title: Ashley Yoon's Portfolio Page
description: Hi! I'm Ashley Yoon, and I'm currently a sophomore at the University of 
Rochester intending on majoring in Computer Science. I'm interested in Software 
Development/Engineering, Full Stack, UX/UI Design, and Mobile App Development. 
I'll be updating this page for my projects -- feel free to look around!
